apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-hello-world-web-b-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  PORT: "4000"
  POD_NAME: "pod b"
  API_VERSION: "version 1"
  POD_PATH: "/pod-b"