apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-hw-b-cm
  namespace: test-b
  labels:
    app: *app-name
data:
  PORT: "4100"
  POD_NAME: "pod b (ns test-b)"
  API_VERSION: "version 1"
  POD_PATH: "/pod-b"