apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-hello-world-web-c-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  PORT: "5000"
  POD_NAME: "pod c"
  API_VERSION: "version 1"
  POD_PATH: ""
