apiVersion: v1
kind: Service
metadata:
  name: &app-name svc-go-hello-world-web
  namespace: test-a
  labels:
    app: *app-name
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30500
    protocol: TCP
  selector:
    app: go-hello-world-web